# Python w Analizie Danych
# Lab02 - Numpy - Sprawozdanie

Autor: Piotr Przymus 127902

### Zadanie 1
Utworzyłem tablicę zawierającą liczby z przedziału <10;80> z krokiem co 5 za pomocą `np.arrange`, wymiary zmieniłem za pomocą `np.reshape`, transpozycja za pomocą `np.T`. Przy losowych wartościach w drugiej tablicy użyłem stałego seeda żeby wyniki były powtarzalne. Obliczyłem sumę wierszy i kolumn, dodatkowo wyświetliłem je - w celach estetycznych użyłem do tego `Pandas` ze stylami (były mi znane wcześniej). Komórkę w prawym dolnym rogu tabeli, zawierającą zarówno `col_sum` oraz `row_sum` podmieniłem na wartość NaN.

In [15]:
import numpy as np
# a
arr = np.arange(10, 81, 5).reshape(5, 3)
print("arr:\n", arr)

# b
print("Transpozycja:\n", arr.T)

# c
from numpy.random import default_rng
rng = default_rng(42)
rand = rng.integers(0, 100, size=(5, 2))
mat = np.hstack([arr, rand])  # 5x5

# d
row_sum = mat.sum(axis=1)
col_sum = mat.sum(axis=0)
total_sum = row_sum.sum()

import pandas as pd

df = pd.DataFrame(mat, columns=[f'col{i}' for i in range(mat.shape[1])])
df['row_sum'] = row_sum
df.loc['col_sum'] = list(col_sum) + [total_sum]

df.loc['col_sum', 'row_sum'] = np.nan

styled = (
    df.style
      .format("{:.2f}", na_rep="")
      .apply(lambda row: ['font-weight: bold; background-color: gray; color: black' if row.name == 'col_sum' else '' for _ in row], axis=1)
      .apply(lambda col: ['font-weight: bold; background-color: gray; color: black' if col.name == 'row_sum' else '' for _ in col], axis=0)
)

styled

arr:
 [[10 15 20]
 [25 30 35]
 [40 45 50]
 [55 60 65]
 [70 75 80]]
Transpozycja:
 [[10 25 40 55 70]
 [15 30 45 60 75]
 [20 35 50 65 80]]


,col0,col1,col2,col3,col4,row_sum
0,10.00,15.00,20.00,8.00,77.00,130.00
1,25.00,30.00,35.00,65.00,43.00,198.00
2,40.00,45.00,50.00,43.00,85.00,263.00
3,55.00,60.00,65.00,8.00,69.00,257.00
4,70.00,75.00,80.00,20.00,9.00,254.00
col_sum,200.00,225.00,250.00,144.00,283.00,


### Zadanie 2
Wczytałem dane z pliku `data_numpy.csv` i wykonałem zadania a-e. W podpunkcie d) ponownie w celach estetycznych zastosowałem `Pandas` ze stylami.

#### Kod źródłowy

In [5]:
# a
data = np.loadtxt('data/data_numpy.csv', delimiter=',')
print('shape:', data.shape)

shape: (15, 25)


In [6]:
# b
col_min = data.min(axis=0)
col_max = data.max(axis=0)
print('col_min:', col_min)
print('col_max:', col_max)

col_min: [ 0.1   4.19  7.77  0.84  8.06 10.62  1.03  9.56 13.64  1.77  1.37  2.6
  6.61 11.31  4.78  8.64  2.31  9.7   3.46  0.09  3.72  2.21 28.76  3.88
  6.27]
col_max: [87.42 85.42 96.75 95.97 80.23 95.76 89.77 92.02 97.4  97.9  90.68 93.93
 95.63 85.03 88.06 98.38 97.43 98.47 93.53 97.   96.02 98.24 87.82 96.05
 99.79]


In [7]:
# c
row_mean = data.mean(axis=1)
row_std = data.std(axis=1)
print('row_mean:', row_mean)
print('row_std:', row_std)

row_mean: [54.908  45.032  51.0704 48.2504 64.4192 50.2476 47.0828 58.0392 52.4724
 58.0624 48.3224 40.9548 53.0524 40.5444 50.2108]
row_std: [25.27275387 27.21587155 28.6332638  26.00175555 25.73154747 36.94823961
 29.85676078 28.63506311 31.42499506 22.19580128 29.52139472 26.43496868
 30.3291087  29.47558136 28.06522758]


In [8]:
# d
import pandas as pd

trans = data.T
df = pd.DataFrame(trans, columns=[f'col{i}' for i in range(trans.shape[1])])
df.loc['mean'] = row_mean
df.loc['std'] = row_std
trans_with_stats = df.values

print('po transpozycji z dodanymi statystykami:', trans_with_stats.shape)
styled = (
    df.style
      .format('{:.2f}')
      .apply(lambda row: ['font-weight: bold; background-color: gray; color: black' if row.name in ('mean','std') else '' for _ in row], axis=1)
)

styled

po transpozycji z dodanymi statystykami: (27, 15)


,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12,col13,col14
0,57.81,39.73,0.10,87.42,62.52,77.26,3.80,24.71,84.80,62.74,26.11,15.66,22.73,11.13,29.62
1,53.34,6.56,40.80,28.03,4.19,82.96,73.94,67.72,17.54,67.90,85.42,71.26,15.46,51.04,41.76
2,96.75,57.39,50.99,7.77,82.27,81.06,77.65,91.04,18.07,83.88,79.91,36.82,70.42,74.41,91.06
3,79.97,61.04,65.90,31.35,95.97,10.08,81.44,19.23,20.91,79.81,0.84,31.78,76.81,17.65,57.30
4,49.37,8.06,46.21,37.60,56.54,25.19,14.17,47.47,30.38,68.51,80.23,10.72,33.79,21.03,17.33
5,78.14,43.63,21.78,60.87,72.20,71.42,69.41,11.27,45.64,56.81,10.62,42.74,83.04,68.10,95.76
6,1.03,83.40,16.40,89.77,56.60,25.01,55.01,25.09,28.21,40.57,14.95,21.44,64.59,9.62,49.74
7,31.45,45.13,74.21,34.47,91.55,78.04,9.56,60.49,76.95,71.43,63.92,92.02,24.10,33.34,85.56
8,60.73,75.77,13.64,41.14,89.19,89.79,17.42,37.60,97.40,43.69,24.05,60.90,88.26,47.87,62.75
9,81.97,1.77,4.12,29.43,14.85,20.33,97.90,46.24,2.31,74.51,40.41,7.13,71.57,7.51,43.93


In [9]:
# e
np.savetxt('data/results_numpy_task2.csv', trans_with_stats, fmt='%.2f', delimiter=',')
print("Zapisano do data/results_numpy_task2.csv")

Zapisano do data/results_numpy_task2.csv


### Zadanie 3
Znormalizowałem dane w kolumnach za pomocą wzoru
$$
\frac{x-min}{max-min}\
$$
używając `col_min` oraz `col_max` z zadania 2b.

#### Kod źródłowy

In [10]:
normalized = (data - col_min) / (col_max - col_min)
print('Znormalizowane dane:\n', normalized[:5])

Znormalizowane dane:
 [[0.66090243 0.60507202 1.         0.8318091  0.5723985  0.79304675
  0.         0.26546204 0.56220153 0.8342869  0.74392565 0.74006351
  0.1656931  0.4234943  0.42735351 0.83953644 0.69428091 0.58567083
  0.57644055 0.50139305 0.86446371 0.03603041 0.50457162 0.69339264
  0.        ]
 [0.45384792 0.02917641 0.55765341 0.63281825 0.         0.38771435
  0.92821726 0.43136066 0.74176218 0.         0.17120143 0.43589182
  0.         0.80927835 0.30235351 0.81401828 0.63467199 0.4619804
  0.06195182 0.71953359 1.         0.22472144 0.27531324 0.23760443
  0.70455518]
 [0.         0.45069556 0.48572713 0.68390623 0.528613   0.13107822
  0.17320261 0.78401649 0.         0.02444606 0.8444743  0.70250739
  0.92911705 0.78540423 1.         0.         0.4103238  0.49059367
  0.97657378 0.28397482 0.45850488 0.77194627 0.9238063  0.90441575
  0.3314799 ]
 [1.         0.29348763 0.         0.32071902 0.40931135 0.59020437
  1.         0.30208586 0.32831901 0.28773536 0.     

### Zadanie 4
Dokonaj konwersji znormalizowanych danych z poprzedniego zadania do klasy `pandas.DataFrame` nadając każdej kolumnie nazwę `col{x}` gdzie `x` to kolejny numer kolumny. Wyświetl przykładowe dane.

Przekonwertowałem znormalizowaną tablicę na `pandas.DataFrame` z kolumnami `col0, col1, ...`. Do wyświetlenia przykładowych (pierwszych 5 wierszy) danych użyłem `df.head()`.

#### Kod źródłowy

In [11]:
import pandas as pd

df = pd.DataFrame(normalized, columns=[f'col{i}' for i in range(normalized.shape[1])])
print(df.head())

       col0      col1      col2      col3      col4      col5      col6  \
0  0.660902  0.605072  1.000000  0.831809  0.572399  0.793047  0.000000   
1  0.453848  0.029176  0.557653  0.632818  0.000000  0.387714  0.928217   
2  0.000000  0.450696  0.485727  0.683906  0.528613  0.131078  0.173203   
3  1.000000  0.293488  0.000000  0.320719  0.409311  0.590204  1.000000   
4  0.714842  0.000000  0.837267  1.000000  0.671747  0.723279  0.626211   

       col7      col8      col9  ...     col15     col16     col17     col18  \
0  0.265462  0.562202  0.834287  ...  0.839536  0.694281  0.585671  0.576441   
1  0.431361  0.741762  0.000000  ...  0.814018  0.634672  0.461980  0.061952   
2  0.784016  0.000000  0.024446  ...  0.000000  0.410324  0.490594  0.976574   
3  0.302086  0.328319  0.287735  ...  0.350903  0.549622  0.916751  0.067281   
4  0.994300  0.901982  0.136066  ...  0.984065  0.786796  0.269122  0.263351   

      col19     col20     col21     col22     col23     col24  
0  0

## Wnioski
- Zadania pomogły mi przypomnieć sobie podstawowe operacje na danych w Numpy.
- Numpy może nie być najlepsze do czytelnego wyświetlania danych - dlatego też użyłem Pandas żeby łatwo dodawać opisowe etykiety (np. "row_sum" albo "mean") oraz styli żeby wynik wyglądał estetycznie.