# Język Python w Analizie Danych
# Numpy

## Cel zajęć
- Poznanie zastosowania modułu `NumPy`.
- Ćwiczenie wykorzystania obiektów klasy `ndarray` i związanych z nimi metod w praktyce.
- Wykonanie zadań ćwiczeniowych z wykorzystaniem modułu.

## Część teoretyczna

### Dokumentacja
- NumPy: https://numpy.org/doc/stable/
- Pandas: https://pandas.pydata.org/docs/

In [1]:
# Import modułu
import numpy as np

### Przykłady

In [34]:
# Tworzenie obiektu ndarray i podstawowe operacje
arr = np.array([[2.5, -.5, 3.1], [.5, -3, 7.5]])
print(arr)
print(arr * 10)
print(arr + arr)
print(arr - arr)
print(arr / 2)

[[ 2.5 -0.5  3.1]
 [ 0.5 -3.   7.5]]
[[ 25.  -5.  31.]
 [  5. -30.  75.]]
[[ 5.  -1.   6.2]
 [ 1.  -6.  15. ]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.25 -0.25  1.55]
 [ 0.25 -1.5   3.75]]


In [35]:
# Atrybuty i agregacje
print(f"ndim: {arr.ndim}")
print(f"shape: {arr.shape}")
print(f"dtype: {arr.dtype}")
print(f"size: {arr.size}")


print(f"min: {arr.min()} at {arr.argmin()}")
print(f"max: {arr.max()} at {arr.argmax()}")
print(f"mean: {arr.mean()}")
print(f"sum: {arr.sum()}")
print(f"prod: {arr.prod()}")
print(f"std: {arr.std()}")
print(f"var: {arr.var()}")


ndim: 2
shape: (2, 3)
dtype: float64
size: 6
min: -3.0 at 4
max: 7.5 at 5
mean: 1.6833333333333333
sum: 10.1
prod: 43.59375
std: 3.2814715533668055
var: 10.768055555555556


In [36]:
print(arr)
print(arr.transpose())

[[ 2.5 -0.5  3.1]
 [ 0.5 -3.   7.5]]
[[ 2.5  0.5]
 [-0.5 -3. ]
 [ 3.1  7.5]]


In [5]:
# Odczyt i zapis plików CSV
arr = np.loadtxt('data/example_data_numpy.csv', delimiter=',', dtype=int)
print(arr)
np.savetxt('data/example_results_numpy.csv', arr, fmt='%.2f', delimiter=',')

[[55 77 77 15 44  6 52 58 32 59]
 [36 44 29 48 69 52 66 69 65 37]
 [69 92 35 31 20 66  1 72 33 17]
 [48 44 11 64 61 41 36 54  2 31]
 [48 55 77 26 70 18 81 68 90 11]
 [18 13 54 16 32 58 94  6 77 95]
 [ 9 76 35 30 53 18 83 54 67 39]
 [44 25 27 57 66 29 69 41 32 53]
 [95 25  0 76 77 75 77 17 63  6]
 [97 15 43 92 53 69 67  7 78 29]
 [11 73 78 66 12 98 88 58  8 27]
 [72 93 79 65 76 39 92 46 49 44]
 [15 28 13 15 72 33 54 64 27 64]
 [87 57 44 34 20 35 96 88 25 30]
 [ 4  6 48 51 99  0 87 60 13  6]]


### Zadanie 1
Utwórz tablicę zawierającą liczby z przedziału <10;80> z krokiem co 5. Następnie wykonaj poniższe operacje:

a) zmień wymiary tablicy na 5x3 (5 wierszy, 3 kolumny)

b) wyświetl jej transpozycję

c) utwórz drugą tablicę 5x2 z losowymi wartościami z przedziau <0;100>. Połącz obie tablice aby otrzymać macierz kwadratową.

d) oblicz sumę wierszy oraz kolumn

In [ ]:
# TODO: Zadanie 1

### Zadanie 2
Wczytaj dane z pliku `data_numpy.csv` i wykonaj operacje z punktów a)-e).

a) wyświetl kształt (rozmiar) tablicy

b) wyznacz wartości minimalne i maksymalne dla każdej kolumny i zapisz je w nowej tablicy (potrzebne do zadania 3)

c) oblicz średnią i odchylenie standardowe dla każdego wiersza

d) w nowej macierzy zapisz transpozycję wczytanych danych. Dodaj na jej końcu nowe wiersze z wartościami średnich i odchylenia standardowego wyliczonych w poprzednim punkcie.

e) zapisz nową macierz z punktu `d)` jako `results_numpy_task2.csv`

#### Kod źródłowy

In [1]:
# TODO: a)

In [ ]:
# TODO: b)
col_min = 0
col_max = 0

In [ ]:
# TODO: c)

In [ ]:
# TODO: d)

In [ ]:
# TODO: e)

### Zadanie 3
Na podstawie pierwotnie wczytanych danych przeskaluj dane tak, aby każda wartość była znormalizowana do zakresu 0-1 względem wartości w kolumnie przy pomocy wzoru
$$
\frac{x-min}{max-min}\
$$
gdzie `x` to normalizowana wartość, `min` to wartość minimalna z kolumny, a `max` to wartość maksymalna z kolumny.

#### Kod źródłowy

In [ ]:
 # TODO: zadanie 3

### Zadanie 4
Dokonaj konwersji znormalizowanych danych z poprzedniego zadania do klasy `pandas.DataFrame` nadając każdej kolumnie nazwę `col{x}` gdzie `x` to kolejny numer kolumny. Wyświetl przykładowe dane.

#### Kod źródłowy

In [ ]:
import pandas as pd
# TODO: zadanie 4

### Sprawozdanie

- plik notatnika `.ipynb` z rozwiązaniami zadań,
- opis stworzonych rozwiązań,
- zrzuty ekranu potwierdzające poprawne działanie kodu lub widoczne wyniki uruchomienia komórek z notatnika jupyter,
- wnioski,
- (opcjonalnie) uwagi i sugestie dotyczące instrukcji i treści laboratorium,
- (opcjonalnie) bibliografię
Sprawozdanie dopuszczalne tylko w formacie `.pdf` lub `.tex` lub `.ipynb`.